### ISSUE TITLE
Trace File Input Format

### ISSUE THREAD

**Issue by bindatype** [BSC-RM/slurm_simulator_tools#2]
Hi, 

I'm trying to set up the slurm simulator and I'm not clear about what the format for the input for swf2trace ought to be. Is there an example or a reference you can share to help me get past this step? 

Thanks in advance!

**Comment by marcodamico** [comment]
Hello,
swf2trace uses the SWF format, available at: https://www.cs.huji.ac.il/labs/parallel/workload/swf.html
you can find workload traces and models in the same website: https://www.cs.huji.ac.il/labs/parallel/workload/
We will soon introduce new features that can directly read text SWF format with no conversion needed.

**Comment by bindatype** [comment]
Thanks for the quick reply!
