### ISSUE TITLE
Install failing

### ISSUE THREAD

**Issue by brdalert** [BSC-RM/slurm_simulator_tools#3]
Hi, I am trying to install your simulator but the make -j4 command is failing. when looking at the output I see these errors in the terminal: slurm_protocol_pack.c: In function ‘_pack_job_desc_msg’:
slurm_protocol_pack.c:8703:24: error: ‘job_desc_msg_t’ {aka ‘struct job_descriptor’} has no member named ‘duration’; did you mean ‘partition’?
   pack32(job_desc_ptr->duration, buffer);
                        ^~~~~~~~
                        partition
In file included from ../../src/common/checkpoint.h:45,
                 from ../../src/slurmctld/slurmctld.h:56,
                 from ../../src/common/slurm_accounting_storage.h:44,
                 from ../../src/common/assoc_mgr.h:48,
                 from slurm_protocol_pack.c:46:
slurm_protocol_pack.c: In function ‘_unpack_job_desc_msg’:
slurm_protocol_pack.c:9184:32: error: ‘job_desc_msg_t’ {aka ‘struct job_descriptor’} has no member named ‘duration’; did you mean ‘partition’?
   safe_unpack32(&job_desc_ptr->duration, buffer);

THis is the output of the:make[4]: Leaving directory '/home/slurm/slurm_simulator_tools/slurm_simulator/src/common'
make[3]: *** [Makefile:1288: ../../src/common/libcommon.la] Error 2
make[3]: Leaving directory '/home/slurm/slurm_simulator_tools/slurm_simulator/src/api'
make[2]: *** [Makefile:1288: ../../src/api/libslurmhelper.la] Error 2
make[2]: Leaving directory '/home/slurm/slurm_simulator_tools/slurm_simulator/src/api'
make[1]: *** [Makefile:547: install-recursive] Error 1
make[1]: Leaving directory '/home/slurm/slurm_simulator_tools/slurm_simulator/src'
make: *** [Makefile:674: install-recursive] Error 1
Compiling simulator binaries
make: *** No targets specified and no makefile found.  Stop.
Installing simulator binaries
make: *** No rule to make target 'install'.  Stop.

**Comment by brdalert** [comment]
I forgot to mention that I tried on both centOS7 and CentOS8

**Comment by daidong** [comment]
just want to know whether this issue has been solved? I have the same error on Ubuntu1804. This happens during compiling slurm_simulator.

`slurm_protocol_pack.c:8703:24: error: ‘job_desc_msg_t {aka struct job_descriptor}’ has no member named ‘duration’; did you mean ‘partition’?
   pack32(job_desc_ptr->duration, buffer);
                        ^~~~~~~~
                        partition
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -I../../slurm -I../.. -DSBINDIR=\"/home/vagrant/gitrepos/slurm_simulator_tools/install/slurm_programs/sbin\" -D SLURM_SIMULATOR -g0 -O3 -D NDEBUG=1 -fno-omit-frame-pointer -fcommon -pthread -MT xlua.lo -MD -MP -MF .deps/xlua.Tpo -c xlua.c -o xlua.o >/dev/null 2>&1
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -I../../slurm -I../.. -DSBINDIR=\"/home/vagrant/gitrepos/slurm_simulator_tools/install/slurm_programs/sbin\" -D SLURM_SIMULATOR -g0 -O3 -D NDEBUG=1 -fno-omit-frame-pointer -fcommon -pthread -MT timers.lo -MD -MP -MF .deps/timers.Tpo -c timers.c -o timers.o >/dev/null 2>&1
In file included from ../../src/common/checkpoint.h:45:0,
                 from ../../src/slurmctld/slurmctld.h:56,
                 from ../../src/common/slurm_accounting_storage.h:44,
                 from ../../src/common/assoc_mgr.h:48,
                 from slurm_protocol_pack.c:46:
slurm_protocol_pack.c: In function ‘_unpack_job_desc_msg’:
slurm_protocol_pack.c:9184:32: error: ‘job_desc_msg_t {aka struct job_descriptor}’ has no member named ‘duration’; did you mean ‘partition’?
   safe_unpack32(&job_desc_ptr->duration, buffer);
                                ^
../../src/common/pack.h:185:22: note: in definition of macro ‘safe_unpack32’
         if (unpack32(valp,buf))    \
                      ^~~~
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -I../../slurm -I../.. -DSBINDIR=\"/home/vagrant/gitrepos/slurm_simulator_tools/install/slurm_programs/sbin\" -D SLURM_SIMULATOR -g0 -O3 -D NDEBUG=1 -fno-omit-frame-pointer -fcommon -pthread -MT gpu.lo -MD -MP -MF .deps/gpu.Tpo -c gpu.c -o gpu.o >/dev/null 2>&1
sim_funcs.c:62:5: error: conflicting types for ‘gettimeofday’
 int gettimeofday(struct timeval *tv, void *tz){
     ^~~~~~~~~~~~
In file included from ../../src/common/sim_funcs.h:23:0,
                 from sim_funcs.c:3:
/usr/include/x86_64-linux-gnu/sys/time.h:68:12: note: previous declaration of ‘gettimeofday’ was here
 extern int gettimeofday (struct timeval *__restrict __tv,`

**Comment by marcodamico** [comment]
The bug has now been fixed!
