### ISSUE TITLE
'Node count specification invalid' when running workload

### ISSUE THREAD

**Issue by armstrongmsg** [BSC-RM/slurm_simulator_tools#6]
I tried to run the simulator using the workload available at http://www.cs.huji.ac.il/labs/parallel/workload/l_kit_fh2/KIT-FH2-2016-1.swf.gz.

I changed the number of records in swf2trace.c, the number of nodes and the number of cores in run_simulation_local.sh. Following the procedure described in the README, I received a 'Node count specification invalid'. Should I change some other configuration to make it work?

[simulation.log](https://github.com/BSC-RM/slurm_simulator_tools/files/7571465/simulation.log)

**Comment by marcodamico** [comment]
Hello,
the simulator should now be able to read swf directly. You can try it by changing the run_simulation_local.sh script, line 56, from:
sim_mgr -f -w $workload
to: 
sim_mgr -f -s $workload

Also, did you configure slurm.conf.template located in the install/slurm_conf folder to reflect the system you want to simulate?

If you use the binary format, to verify that your trace is in the correct format you can:
1- Use list_trace: ./install/slurm_programs/bin/list_trace -w workloads/cirne_workload 
2- activate debug in sim_mgr to print the complete input trace by enabling the function displayJobTraceT() in slurm_simulator/contribs/simulator/sim_mgr.c

**Comment by armstrongmsg** [comment]
I used list_trace to check the workload binary and it showed that the value in the Tasks column was 0 when tasks < CPUS_PER_NODE. Since this probably was the cause of the problem, I modified swf2trace.c, adding the lines 
```
if (!job_arr[idx].tasks) {
        job_arr[idx].tasks = 1;
}
```
It seems this change fixed the issue as the error no longer appears.
